import assert from 'node:assert/strict';
import {rapidFireQuestions} from '../src/data/rapidFire.js';
import {chainCards} from '../src/data/chainGame.js';
import {oneWordCards} from '../src/data/oneWordGame.js';
import {directorCards} from '../src/data/directorGame.js';
import {threeSecondCards} from '../src/data/threeSecondGame.js';
import {quotePrompts} from '../src/data/quoteGame.js';
import fs from 'node:fs';
let n=0; const ok=(name,cond)=>{assert.ok(cond,name);n++;console.log('PASS',name)};
const unique=(a,key)=>new Set(a.map(x=>x[key].trim().toLowerCase())).size===a.length;
ok('rapid prompts unique',unique(rapidFireQuestions,'prompt'));
ok('chain topics unique',unique(chainCards,'title'));
ok('chain has explicit examples',chainCards.every(x=>x.examples && !x.examples.includes('مجری یک نمونه روشن')));
ok('chain examples are varied',new Set(chainCards.map(x=>x.examples)).size>110);
ok('one-word targets unique',unique(oneWordCards,'target'));
ok('one-word has three forbidden words',oneWordCards.every(x=>x.forbidden.length===3));
ok('one-word difficulty mixed per category',[...new Set(oneWordCards.map(x=>x.category))].every(c=>new Set(oneWordCards.filter(x=>x.category===c).map(x=>x.difficulty)).size===3));
ok('director scenes unique',unique(directorCards,'scene'));
ok('director twists unique',unique(directorCards,'twist'));
ok('director roles highly varied',new Set(directorCards.map(x=>x.role)).size>=110);
ok('director constraints highly varied',new Set(directorCards.map(x=>x.constraint)).size>=110);
ok('director difficulty exactly balanced',[1,2,3].every(d=>directorCards.filter(x=>x.difficulty===d).length===40));
ok('three-second prompts unique',unique(threeSecondCards,'prompt'));
ok('three-second category spread',new Set(threeSecondCards.map(x=>x.category)).size===15);
ok('quote prompts unique',unique(quotePrompts,'prompt'));
ok('quote category spread',new Set(quotePrompts.map(x=>x.category)).size===12);
const ow=fs.readFileSync(new URL('../src/screens/OneWordGame.jsx',import.meta.url),'utf8');
ok('one-word removes redundant reveal',!ow.includes('جواب رو لو بده')&&!ow.includes('setRevealed'));
ok('one-word privacy cue',ow.includes('فقط دست راهنما'));
console.log(`CONTENT POLISH V35 ${n}/${n} PASS`);
