import assert from 'node:assert/strict';import fs from'node:fs';
import{rapidFireQuestions,RAPID_FIRE_SECONDS}from'../src/data/rapidFire.js';import{chainCards,CHAIN_TURN_SECONDS}from'../src/data/chainGame.js';import{oneWordCards,ONE_WORD_SECONDS}from'../src/data/oneWordGame.js';import{directorCards,DIRECTOR_SECONDS}from'../src/data/directorGame.js';import{threeSecondCards,THREE_SECOND_MS}from'../src/data/threeSecondGame.js';import{quotePrompts,QUOTE_GUESS_MS}from'../src/data/quoteGame.js';
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};const norm=s=>String(s).normalize('NFKC').replace(/[\u200c\s؟?!،,.«»"'ـ]/g,'').toLowerCase();const unique=(a,key)=>new Set(a.map(x=>norm(key(x)))).size===a.length;
const banks=[['rapid',rapidFireQuestions,x=>x.prompt],['chain',chainCards,x=>x.title],['oneword',oneWordCards,x=>x.target],['director',directorCards,x=>x.scene],['three',threeSecondCards,x=>x.prompt],['quote',quotePrompts,x=>x.prompt]];
for(const[name,a,key]of banks){ok(a.length>=120,`${name} bank size`);ok(new Set(a.map(x=>x.id)).size===a.length,`${name} ids unique`);ok(unique(a,key),`${name} prompt unique`);ok(a.every(x=>key(x)?.trim()),`${name} nonempty`)}
ok(RAPID_FIRE_SECONDS===45&&CHAIN_TURN_SECONDS===5&&ONE_WORD_SECONDS===45&&DIRECTOR_SECONDS===60&&THREE_SECOND_MS===3000&&QUOTE_GUESS_MS===15000,'timers data-owned');
ok(chainCards.every(x=>x.examples&&!x.examples.includes('نمونه روشن')&&[1,2,3].includes(x.difficulty)),'chain examples curated + difficulty');
ok(oneWordCards.every(x=>x.forbidden.length===3&&x.forbidden.every(f=>norm(f)!==norm(x.target))&&[1,2,3].includes(x.difficulty)),'oneword forbidden/difficulty');
ok(directorCards.every(x=>x.role&&x.emotion&&x.constraint&&x.twist&&[1,2,3].includes(x.difficulty)),'director complete cards');
ok(threeSecondCards.every(x=>Array.isArray(x.examples)&&x.examples.length===3&&[1,2,3].includes(x.difficulty)),'three-second examples/difficulty');
ok(quotePrompts.every(x=>[1,2,3].includes(x.difficulty)),'quote difficulty');
for(const f of ['RapidFire','ChainGame','OneWordGame','DirectorGame','ThreeSecondGame','QuoteGame']){const s=fs.readFileSync(new URL(`../src/screens/${f}.jsx`,import.meta.url),'utf8');ok(/Rules|قانون|Rules/.test(s)||s.includes('Rules'),`${f} intro rules structure`);ok(s.includes("phase==='intro'")||s.includes('phase==="intro"'),`${f} intro first`)}
const modes=fs.readFileSync(new URL('../src/screens/PartyModes.jsx',import.meta.url),'utf8');ok(!modes.includes('PROMPTS='),'no obsolete demo prompt bank');ok(modes.includes('قبل از شروع هر بازی'),'mode hub explains per-game rules');
const quote=fs.readFileSync(new URL('../src/screens/QuoteGame.jsx',import.meta.url),'utf8');ok(quote.includes('timeoutCounted')&&quote.includes('setMisses(x=>x+1)'), 'quote timeout counted as miss');ok(!quote.includes('.sort(()=>Math.random()-.5)'), 'quote unbiased shuffle');
const one=fs.readFileSync(new URL('../src/screens/OneWordGame.jsx',import.meta.url),'utf8'),three=fs.readFileSync(new URL('../src/screens/ThreeSecondGame.jsx',import.meta.url),'utf8');ok(!one.includes('.sort(()=>Math.random()-.5)')&&!three.includes('.sort(()=>Math.random()-.5)'),'unbiased mini-game shuffles');
const vite=fs.readFileSync(new URL('../vite.config.js',import.meta.url),'utf8'),workflow=fs.readFileSync(new URL('../.github/workflows/deploy.yml',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/styles/app.css',import.meta.url),'utf8');ok(vite.includes('base:"./"')&&vite.includes('start_url:"./"')&&vite.includes('scope:"./"'),'GitHub Pages relative base/PWA');ok(workflow.includes('npm run test:audit')&&workflow.includes('path: ./dist'),'Pages QA before deploy');ok(html.includes('viewport-fit=cover')&&html.includes('dir="rtl"'),'RTL + iPhone viewport');ok(css.includes('focus-visible')&&css.includes('safe-area-inset-bottom')&&css.includes('100dvh'),'interaction/safe-area hardening');
const allText=fs.readFileSync(new URL('../src/data/questions.js',import.meta.url),'utf8')+fs.readFileSync(new URL('../src/data/oneWordGame.js',import.meta.url),'utf8');ok(!allText.includes('پالینڈروم')&&!allText.includes('کند‌و')&&chainCards.every(x=>!x.examples.includes('نمونه روشن')),'known content defects removed');
console.log(`FINAL DEEP QA V33 ${n}/${n} PASS`);
