import React,{useEffect,useMemo,useRef,useState}from"react";
import GameShell from"../components/GameShell";
import{PartySessionSetup,MiniScoreboard,emptyScores}from"../components/PartySessionSetup";import{PartyChampion,partyCue}from"../components/PartyGameFeel";
import{directorCards,DIRECTOR_SECONDS}from"../data/directorGame";
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
export default function DirectorGame({back}){
 const[phase,setPhase]=useState('intro'),[rounds,setRounds]=useState(3),[scores,setScores]=useState({}),[deck,setDeck]=useState(()=>shuffle(directorCards)),[index,setIndex]=useState(0),[left,setLeft]=useState(DIRECTOR_SECONDS),[prep,setPrep]=useState(5),[twist,setTwist]=useState(false),[wins,setWins]=useState(0),[cuts,setCuts]=useState(0),[playersText,setPlayersText]=useState(''),[turn,setTurn]=useState(0);const lock=useRef(false);
 const card=deck[index%deck.length];const players=useMemo(()=>playersText.split(/[،,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,12),[playersText]);const actor=players.length?players[turn%players.length]:'بازیگر';const round=Math.floor(turn/Math.max(1,players.length))+1,total=players.length*rounds;const packs=useMemo(()=>new Set(directorCards.map(x=>x.category)).size,[]);
 useEffect(()=>{if(phase!=='prep')return;const id=setInterval(()=>setPrep(x=>{if(x<=1){setPhase('play');setLeft(DIRECTOR_SECONDS);return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);useEffect(()=>{if(phase!=='play')return;const id=setInterval(()=>setLeft(x=>{if(x<=1){setPhase('judge');return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);
 const start=()=>{if(players.length<2)return;setScores(emptyScores(players));setDeck(shuffle(directorCards));setIndex(0);setLeft(DIRECTOR_SECONDS);setTwist(false);setWins(0);setCuts(0);setTurn(0);setPrep(5);setPhase('prep')};
 const next=ok=>{if(lock.current)return;lock.current=true;if(ok){partyCue('good');setScores(s=>({...s,[actor]:(s[actor]||0)+1}));setWins(x=>x+1)}else{partyCue('bad');setCuts(x=>x+1)};setIndex(x=>x+1);setTurn(x=>x+1);setLeft(DIRECTOR_SECONDS);setTwist(false);setPrep(5);if(turn+1>=total)setPhase('result');else setPhase('prep');setTimeout(()=>lock.current=false,80)};
 if(phase==='intro')return <GameShell><button className="backBtn" onClick={back}>→ بازی‌های دیگر</button><section className="dirIntro"><div className="dirMark">🎬</div><span className="eyebrow">کارگردان</span><h1>صحنه آماده‌ست.</h1><p>هر اجرای موفق یک امتیاز برای بازیگر همان نوبت.</p></section><PartySessionSetup title="مسابقه کارگردان" playersText={playersText} setPlayersText={setPlayersText} rounds={rounds} setRounds={setRounds} onStart={()=>start()}/><small className="bankCount">بانک بازی: {directorCards.length} صحنه در {packs} ژانر</small></GameShell>;
 if(phase==='prep')return <GameShell><MiniScoreboard players={players} scores={scores} current={actor} round={round} rounds={rounds}/><div className="dirTop"><div><span className="eyebrow">برداشت {index+1} · آماده‌سازی</span><strong>{actor}، کارت رو بگیر</strong></div><div className="dirClock prep"><strong>{prep}</strong><small>ثانیه</small></div></div><section className="dirCard"><div className="dirGenre">{card.category} · سختی {card.difficulty}</div><small>موقعیت</small><h1>{card.scene}</h1><div className="dirSpecs"><div><small>🎭 نقش</small><strong>{card.role}</strong></div><div><small>🎚️ حس غالب</small><strong>{card.emotion}</strong></div><div><small>🚫 قانون صحنه</small><strong>{card.constraint}</strong></div></div><div className="dirPrepNote">۵ ثانیه فقط برای خواندن کارت؛ بعد تایمر ۶۰ ثانیه‌ای اجرا خودکار شروع می‌شود.</div></section></GameShell>;
 if(phase==='judge')return <GameShell><MiniScoreboard players={players} scores={scores} current={actor} round={round} rounds={rounds}/><section className="dirJudgeScreen"><span className="eyebrow">پایان برداشت</span><div className="dirMark">🎬</div><h1>کات! نظر کارگردان؟</h1><p><b>{actor}</b> باید موقعیت، حس و محدودیت کارت را تا آخر نگه می‌داشت.</p><div className="dirStats"><span>گرفتیم <b>{wins}</b></span><span>کات <b>{cuts}</b></span></div></section><div className="dirVerdict"><button onClick={()=>next(false)}>✂️ کات!<small>این یکی نگرفت</small></button><button onClick={()=>next(true)}>✓ گرفتیم!<small>صحنه قبول شد</small></button></div><button className="ghost" onClick={()=>setPhase('result')}>پایان بازی</button></GameShell>;
 if(phase==='result')return <GameShell><PartyChampion title="ستاره کارگردان" players={players} scores={scores} onRestart={()=>setPhase('intro')} onBack={back}/></GameShell>;
 return <GameShell><MiniScoreboard players={players} scores={scores} current={actor} round={round} rounds={rounds}/><div className="dirTop"><div><span className="eyebrow">برداشت {index+1}</span><strong>{actor}، صحنه مال توئه</strong></div><div className={`dirClock ${left<=10?'danger':''}`}><strong>{left}</strong><small>ثانیه</small></div></div><section className="dirCard"><div className="dirGenre">{card.category} · سختی {card.difficulty}</div><small>موقعیت</small><h1>{card.scene}</h1><div className="dirSpecs"><div><small>🎭 نقش</small><strong>{card.role}</strong></div><div><small>🎚️ حس غالب</small><strong>{card.emotion}</strong></div><div><small>🚫 قانون صحنه</small><strong>{card.constraint}</strong></div></div>{twist?<div className="dirTwist revealed"><small>⚡ پیچ داستانی</small><strong>{card.twist}</strong><span>بدون توقف ادامه بده!</span></div>:<button className="dirTwist" onClick={()=>setTwist(true)}><b>⚡ پیچ داستانی رو بنداز</b><small>بهتره وسط اجرا رو بشه</small></button>}</section><div className="dirBottom"><button className="ghost" onClick={()=>setPhase('judge')}>✂️ کات زودتر</button><span>{wins} گرفتیم · {cuts} کات</span></div></GameShell>;
}
/* Rules: قوانین شروع بازی در PartySessionSetup نمایش داده می‌شود. */
