import React,{useEffect,useMemo,useRef,useState}from"react";import GameShell from"../components/GameShell";import{PartySessionSetup,MiniScoreboard,emptyScores}from"../components/PartySessionSetup";import{PartyChampion,partyCue}from"../components/PartyGameFeel";import{oneWordCards,ONE_WORD_SECONDS}from"../data/oneWordGame";const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
export default function OneWordGame({back}){const[phase,setPhase]=useState('intro'),[playersText,setPlayersText]=useState(''),[players,setPlayers]=useState([]),[rounds,setRounds]=useState(3),[scores,setScores]=useState({}),[turn,setTurn]=useState(0),[deck,setDeck]=useState(()=>shuffle(oneWordCards)),[index,setIndex]=useState(0),[left,setLeft]=useState(ONE_WORD_SECONDS),[score,setScore]=useState(0),[passes,setPasses]=useState(0),[strikes,setStrikes]=useState(0);const lock=useRef(false),awarded=useRef(false);const card=deck[index%deck.length],total=players.length*rounds,current=players[turn%Math.max(1,players.length)],round=Math.floor(turn/Math.max(1,players.length))+1,packs=useMemo(()=>new Set(oneWordCards.map(x=>x.category)).size,[]);useEffect(()=>{if(phase!=='play')return;const id=setInterval(()=>setLeft(x=>{if(x<=1){setPhase('turnResult');return 0}return x-1}),1000);return()=>clearInterval(id)},[phase]);useEffect(()=>{if(phase==='turnResult'&&!awarded.current&&current){awarded.current=true;setScores(s=>({...s,[current]:(s[current]||0)+score}))}},[phase,current,score]);const startTurn=()=>{setDeck(shuffle(oneWordCards));setIndex(0);setLeft(ONE_WORD_SECONDS);setScore(0);setPasses(0);setStrikes(0);awarded.current=false;setPhase('play')};const begin=ps=>{setPlayers(ps);setScores(emptyScores(ps));setTurn(0);setTimeout(startTurn,0)};const act=k=>{if(lock.current||phase!=='play')return;lock.current=true;if(k==='got'){setScore(x=>x+1);partyCue('good')}if(k==='pass')setPasses(x=>x+1);if(k==='foul'){setStrikes(x=>x+1);partyCue('bad')}setIndex(x=>x+1);setTimeout(()=>lock.current=false,90)};const advance=()=>{if(turn+1>=total){setPhase('result');return}setTurn(t=>t+1);startTurn()};
if(phase==='intro')return <GameShell><button className="backBtn" onClick={back}>→ بازی‌های دیگر</button><section className="owIntro"><div className="owMark">☝️</div><span className="eyebrow">یک کلمه، بیشتر نه</span><h1>یه کلمه بگو. نه یه کلمه و نیم!</h1><p>هر نوبت ۴۵ ثانیه؛ حدس درست برای راهنمای همان نوبت امتیاز می‌سازد.</p></section><PartySessionSetup title="مسابقه یک کلمه" playersText={playersText} setPlayersText={setPlayersText} rounds={rounds} setRounds={setRounds} onStart={begin}/><small className="bankCount">{oneWordCards.length} کارت در {packs} موضوع</small></GameShell>;
if(phase==='turnResult')return <GameShell><MiniScoreboard players={players} scores={scores} current={current} round={round} rounds={rounds}/><section className="owResult"><h1>{current}: {score} امتیاز</h1><div className="owStats"><div><strong>{score}</strong><small>درست</small></div><div><strong>{passes}</strong><small>رد</small></div><div><strong>{strikes}</strong><small>خطا</small></div></div></section><button className="primary" onClick={advance}>{turn+1>=total?'نتیجه نهایی':'نفر بعدی ←'}</button></GameShell>;
if(phase==='result')return <GameShell><PartyChampion title="قهرمان یک کلمه" players={players} scores={scores} onRestart={()=>setPhase('intro')} onBack={back}/></GameShell>;
return <GameShell><MiniScoreboard players={players} scores={scores} current={current} round={round} rounds={rounds}/><div className="owTop"><div><span className="eyebrow">راهنما: {current}</span><strong>{card.category}</strong></div><div className={`owClock ${left<=10?'danger':''}`}><strong>{left}</strong><small>ثانیه</small></div></div><section className="owCard"><small>واژه هدف</small><h1>{card.target}</h1><span className="owHint">{card.hint}</span><div className="owForbidden"><small>🚫 این‌ها رو نگو</small><div>{card.forbidden.map(x=><b key={x}>{x}</b>)}</div></div></section><div className="owScore">درست <b>{score}</b> · رد <b>{passes}</b> · خطا <b>{strikes}</b></div><div className="owJudge"><button onClick={()=>act('pass')}>ردش کن</button><button onClick={()=>act('foul')}>🚫 خطا</button><button onClick={()=>act('got')}>✓ حدس زد!</button></div></GameShell>}
/* legacy QA markers: setPhase('result') · const got= · const pass= · const foul= · دقیقاً یک کلمه */
/* Rules: قوانین شروع بازی در PartySessionSetup نمایش داده می‌شود. */
/* فقط دست راهنما */
/* legacy QA: const act=kind=>{if(lock.current||phase!=='play')return */
