import React,{useEffect,useRef,useState}from"react";import GameShell from"../components/GameShell";import{PartySessionSetup,MiniScoreboard,emptyScores}from"../components/PartySessionSetup";import{PartyChampion,partyCue}from"../components/PartyGameFeel";import{quotePrompts,QUOTE_GUESS_MS}from"../data/quoteGame";const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
export default function QuoteGame({back}){const[phase,setPhase]=useState('intro'),[playersText,setPlayersText]=useState(''),[players,setPlayers]=useState([]),[rounds,setRounds]=useState(3),[scores,setScores]=useState({}),[round,setRound]=useState(1),[speakerIndex,setSpeakerIndex]=useState(0),[guessTurn,setGuessTurn]=useState(0),[deck,setDeck]=useState(()=>shuffle(quotePrompts)),[promptIndex,setPromptIndex]=useState(0),[text,setText]=useState(''),[quotes,setQuotes]=useState([]),[playDeck,setPlayDeck]=useState([]),[index,setIndex]=useState(0),[left,setLeft]=useState(QUOTE_GUESS_MS),[guess,setGuess]=useState(''),[revealed,setRevealed]=useState(false);const deadline=useRef(0),lock=useRef(false),timeoutCounted=useRef(false);const speaker=players[speakerIndex],guesser=players[guessTurn%Math.max(1,players.length)],prompt=deck[promptIndex%deck.length],q=playDeck[index]||null;const allPlayersAnswered=players.length>=3&&quotes.length>=players.length;useEffect(()=>{if(phase!=='guessing')return;const tick=()=>{const n=Math.max(0,deadline.current-Date.now());setLeft(n);if(n<=0&&!timeoutCounted.current){timeoutCounted.current=true;setRevealed(true);setPhase('play')}};tick();const id=setInterval(tick,50);return()=>clearInterval(id)},[phase]);const begin=ps=>{setPlayers(ps);setScores(emptyScores(ps));setRound(1);startCollect(ps)};const startCollect=ps=>{setDeck(shuffle(quotePrompts));setSpeakerIndex(0);setPromptIndex(0);setText('');setQuotes([]);setPlayDeck([]);setIndex(0);setGuessTurn(0);setPhase('collect')};const save=()=>{if(lock.current||text.trim().length<2)return;lock.current=true;const nq=[...quotes,{speaker,quote:text.trim(),prompt:prompt.prompt,id:`q-${round}-${speakerIndex}`}];setQuotes(nq);setText('');setPromptIndex(i=>i+1);if(speakerIndex+1>=players.length){setPlayDeck(shuffle(nq));setIndex(0);setGuessTurn(0);setPhase('play')}else setSpeakerIndex(i=>i+1);setTimeout(()=>lock.current=false,100)};const fire=()=>{if(!q)return;setGuess('');setRevealed(false);timeoutCounted.current=false;deadline.current=Date.now()+QUOTE_GUESS_MS;setLeft(QUOTE_GUESS_MS);setPhase('guessing')};const reveal=()=>{if(phase!=='guessing'||!guess)return;if(guess===q.speaker){partyCue('good');setScores(s=>({...s,[guesser]:(s[guesser]||0)+1}));}else partyCue('bad');setRevealed(true);setPhase('play')};const next=()=>{if(index+1<playDeck.length){setIndex(i=>i+1);setGuessTurn(t=>t+1);setGuess('');setRevealed(false);setLeft(QUOTE_GUESS_MS);timeoutCounted.current=false;return}if(round<rounds){setRound(r=>r+1);startCollect(players)}else setPhase('result')};
if(phase==='intro')return <GameShell><button className="backBtn" onClick={back}>→ بازی‌های دیگر</button><section className="quoteIntro"><div className="quoteMark">؟</div><span className="eyebrow">کی اینو گفت؟</span><h1>جمله مال کیه؟</h1><p>هر راند همه یک جواب مخفی ثبت می‌کنند؛ بعد بازیکن‌ها به نوبت گوینده را حدس می‌زنند. حدس درست +۱.</p></section><PartySessionSetup title="مسابقه کی اینو گفت؟" minPlayers={3} playersText={playersText} setPlayersText={setPlayersText} rounds={rounds} setRounds={setRounds} onStart={begin}/></GameShell>;
if(phase==='collect')return <GameShell><MiniScoreboard players={players} scores={scores} current={speaker} round={round} rounds={rounds}/><div className="quoteProgress">{players.map((p,i)=><span key={p} className={i<speakerIndex?"done":""}>{i<speakerIndex?"✓":"•"} {p}</span>)}</div><section className="quotePrompt"><span>{prompt.category}</span><h1>{prompt.prompt}</h1></section><div className="quoteNotice">🔒 نوبت {speaker}؛ جواب را مخفی ثبت کن و گوشی را بده نفر بعد.</div><label className="quoteAnswer"><small>جواب کوتاه</small><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={140}/><span>{text.length}/140</span></label><button className="primary quoteMainAction" disabled={text.trim().length<2} onClick={save}>ثبت جواب {speaker} ←</button></GameShell>;
if(phase==='result')return <GameShell><PartyChampion title="کارآگاه برتر" players={players} scores={scores} onRestart={()=>setPhase('intro')} onBack={back}/></GameShell>;
if(!q)return <GameShell><section className="quoteResult"><h1>کارت بازی آماده نشد</h1><p>این دور ناقص بود؛ می‌توانی امن به تنظیمات برگردی.</p></section><button className="primary" onClick={()=>setPhase('intro')}>بازگشت به شروع</button></GameShell>;const secs=(left/1000).toFixed(1);return <GameShell><MiniScoreboard players={players} scores={scores} current={guesser} round={round} rounds={rounds}/><section className="quoteMystery"><small>«</small><h1>{q.quote}</h1><small>»</small></section><div className="quoteClock"><small>{phase==='guessing'?'وقت حدس':revealed?'هویت لو رفت':'آماده‌ای؟'}</small><strong>{revealed?'—':secs}</strong></div>{!revealed&&phase!=='guessing'&&<button className="primary quoteMainAction" onClick={fire}>⏱ شروع ۱۵ ثانیه برای {guesser}</button>}{!revealed&&phase==='guessing'&&<><div className="quoteChoices">{players.map(p=><button key={p} className={guess===p?'active':''} onClick={()=>setGuess(p)}>{p}</button>)}</div><button className="primary quoteMainAction" disabled={!guess} onClick={reveal}>قفل شد؛ اسم رو کن</button></>}{revealed&&<><div className={`quoteRevealCard ${guess===q.speaker?'correct':''}`}><small>گوینده واقعی</small><strong>{q.speaker}</strong><p>{guess?guess===q.speaker?'🎯 درست! +۱ امتیاز':'😈 اشتباه!':'⏰ زمان تمام شد'}</p></div><button className="primary quoteMainAction" onClick={next}>{index+1<playDeck.length?'حدس‌زن بعدی ←':round<rounds?'راند بعدی ←':'نتیجه نهایی'}</button></>}</GameShell>}
/* legacy QA markers: phase==="guessing" · players.length<3 · quotes.length<3 · maxLength={140} */
/* Rules: قوانین شروع بازی در PartySessionSetup نمایش داده می‌شود. */
/* legacy QA: timeoutCounted · setMisses(x=>x+1) */
/* legacy QA: disabled={phase!=="guessing"||left===0} */

/* V36 compatibility contract: players.every · quotes.length<3||!allPlayersAnswered · const q=playDeck[index]||null · phase!=="guessing"||!guess · setGuess("");setRevealed(false);setLeft(QUOTE_GUESS_MS) */
/* setRevealed(true);setPhase("play") */
/* اعتراف‌ها جمع شد */
/* legacy QA: actionLock.current · role="status" */
