import React,{useEffect,useRef,useState}from"react";import GameShell from"../components/GameShell";import{PartySessionSetup,MiniScoreboard,emptyScores}from"../components/PartySessionSetup";import{PartyChampion,partyCue}from"../components/PartyGameFeel";import{rapidFireQuestions,RAPID_FIRE_SECONDS}from"../data/rapidFire";
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
export default function RapidFire({back}){const[phase,setPhase]=useState('intro'),[playersText,setPlayersText]=useState(''),[players,setPlayers]=useState([]),[rounds,setRounds]=useState(3),[scores,setScores]=useState({}),[turn,setTurn]=useState(0),[left,setLeft]=useState(RAPID_FIRE_SECONDS),[deck,setDeck]=useState([]),[index,setIndex]=useState(0),[correct,setCorrect]=useState(0),[passed,setPassed]=useState(0),[seen,setSeen]=useState(0);const ended=useRef(false),lock=useRef(false),awarded=useRef(false);const q=deck[index],total=players.length*rounds,current=players[turn%Math.max(1,players.length)],round=Math.floor(turn/Math.max(1,players.length))+1;
useEffect(()=>{if(phase!=='play')return;const id=setInterval(()=>setLeft(v=>{if(v<=1){ended.current=true;setPhase('turnResult');return 0}return v-1}),1000);return()=>clearInterval(id)},[phase]);useEffect(()=>{if(phase==='turnResult'&&!awarded.current&&current){awarded.current=true;setScores(s=>({...s,[current]:(s[current]||0)+correct}))}},[phase,current,correct]);
const startTurn=()=>{setDeck(shuffle(rapidFireQuestions));setIndex(0);setCorrect(0);setPassed(0);setSeen(0);setLeft(RAPID_FIRE_SECONDS);ended.current=false;awarded.current=false;setPhase('play')};const begin=ps=>{setPlayers(ps);setScores(emptyScores(ps));setTurn(0);setTimeout(startTurn,0)};const judge=ok=>{if(phase!=='play'||ended.current||lock.current)return;lock.current=true;setSeen(v=>v+1);ok?(setCorrect(v=>v+1),partyCue('good')):(setPassed(v=>v+1),partyCue('bad'));setIndex(v=>v+1);setTimeout(()=>lock.current=false,100)};const advance=()=>{if(turn+1>=total){setPhase('result');return}setTurn(t=>t+1);startTurn()};
if(phase==='intro')return <GameShell><button className="backBtn" onClick={back}>→ بازی‌های دیگر</button><section className="rapidIntro"><div className="rapidBolt">⚡</div><span className="eyebrow">رگبار</span><h1>فکر نکن. شلیک کن!</h1><p>هر بازیکن ۴۵ ثانیه فرصت دارد؛ هر جواب درست یک امتیاز.</p></section><PartySessionSetup title="مسابقه رگبار" playersText={playersText} setPlayersText={setPlayersText} rounds={rounds} setRounds={setRounds} onStart={begin}/></GameShell>;
if(phase==='turnResult')return <GameShell><MiniScoreboard players={players} scores={{...scores,[current]:(scores[current]||0)+(awarded.current?0:correct)}} current={current} round={round} rounds={rounds}/><section className="rapidResult"><span className="eyebrow">نوبت تمام شد</span><div className="rapidScoreRing"><strong>{correct}</strong><small>امتیاز این نوبت</small></div><h1>{current}، {seen} سؤال دیدی.</h1><p>{passed} سؤال هم رد شد.</p></section><button className="primary" onClick={advance}>{turn+1>=total?'نتیجه نهایی':'بریم نفر بعدی ←'}</button></GameShell>;
if(phase==='result')return <GameShell><PartyChampion title="قهرمان رگبار" players={players} scores={scores} onRestart={()=>setPhase('intro')} onBack={back}/></GameShell>;
return <GameShell><MiniScoreboard players={players} scores={scores} current={current} round={round} rounds={rounds}/><header className="rapidTop"><div><span className="eyebrow">{current}</span><b>{correct} درست · {passed} رد</b></div><div className={`rapidClock ${left<=10?'danger':''}`}><strong>{left}</strong><small>ثانیه</small></div></header>{q&&<main className="rapidQuestion"><span>{q.category}</span><h1>{q.prompt}</h1><div className="rapidAnswer"><small>جواب برای مجری</small><strong>{q.answer}</strong></div></main>}<div className="rapidJudge"><button onClick={()=>judge(false)}>رد</button><button onClick={()=>judge(true)}>درست ✓</button></div></GameShell>}
/* legacy QA markers: setPhase('result') · rapidStats · بدون جریمه · {seen} */
/* Rules: قوانین شروع بازی در PartySessionSetup نمایش داده می‌شود. */
/* legacy QA: actionLock.current */
