import React,{useEffect,useMemo,useRef,useState}from"react";
import GameShell from"../components/GameShell";
import{PartySessionSetup,MiniScoreboard,emptyScores}from"../components/PartySessionSetup";import{PartyChampion,partyCue}from"../components/PartyGameFeel";
import{threeSecondCards,THREE_SECOND_MS}from"../data/threeSecondGame";
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const namesFrom=s=>s.split(/[،,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,12);
export default function ThreeSecondGame({back}){
 const[phase,setPhase]=useState("intro"),[rounds,setRounds]=useState(3),[scores,setScores]=useState({}),[deck,setDeck]=useState(()=>shuffle(threeSecondCards)),[index,setIndex]=useState(0),[playersText,setPlayersText]=useState(""),[turn,setTurn]=useState(0),[leftMs,setLeftMs]=useState(THREE_SECOND_MS),[wins,setWins]=useState(0),[fails,setFails]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0);const deadline=useRef(0),lock=useRef(false);
 const players=useMemo(()=>namesFrom(playersText),[playersText]),player=players.length?players[turn%players.length]:"بازیکن",round=Math.floor(turn/Math.max(1,players.length))+1,total=players.length*rounds,card=deck[index%deck.length],packs=useMemo(()=>new Set(threeSecondCards.map(x=>x.category)).size,[]);
 useEffect(()=>{if(phase!=="running")return;const tick=()=>{const n=Math.max(0,deadline.current-Date.now());setLeftMs(n);if(n<=0)setPhase("judge")};tick();const id=setInterval(tick,40);return()=>clearInterval(id)},[phase]);
 const fresh=()=>{if(players.length<2)return;setScores(emptyScores(players));setDeck(shuffle(threeSecondCards));setIndex(0);setTurn(0);setWins(0);setFails(0);setStreak(0);setBest(0);setLeftMs(THREE_SECOND_MS);setPhase("ready")};
 const fire=()=>{deadline.current=Date.now()+THREE_SECOND_MS;setLeftMs(THREE_SECOND_MS);setPhase("running")};
 const verdict=ok=>{if(lock.current)return;lock.current=true;if(ok){partyCue('good');setScores(s=>({...s,[player]:(s[player]||0)+1}));setWins(x=>x+1);setStreak(x=>{const n=x+1;setBest(b=>Math.max(b,n));return n})}else{partyCue('bad');setFails(x=>x+1);setStreak(0)}if(turn+1>=total){setPhase("result");}else{setIndex(x=>x+1);setTurn(x=>x+1);setLeftMs(THREE_SECOND_MS);setPhase("ready");}setTimeout(()=>lock.current=false,80)};
 if(phase==="intro")return <GameShell><button className="backBtn" onClick={back}>→ بازی‌های دیگر</button><section className="threeIntro"><div className="threeBadge">3</div><span className="eyebrow">سه‌ثانیه</span><h1>سه جواب. سه ثانیه. همین!</h1><p>هر جواب موفق یک امتیاز برای بازیکن همان نوبت دارد.</p></section><PartySessionSetup title="مسابقه سه‌ثانیه" playersText={playersText} setPlayersText={setPlayersText} rounds={rounds} setRounds={setRounds} onStart={()=>fresh()}/><small className="bankCount">بانک بازی: {threeSecondCards.length} کارت در {packs} موضوع</small></GameShell>;
 if(phase==="result")return <GameShell><PartyChampion title="قهرمان سه‌ثانیه" players={players} scores={scores} onRestart={fresh} onBack={back}/></GameShell>;
 const secs=(leftMs/1000).toFixed(1);const danger=phase==="running"&&leftMs<=1000;
 return <GameShell><MiniScoreboard players={players} scores={scores} current={player} round={round} rounds={rounds}/><div className="threeTop"><div><span className="eyebrow">کارت {index+1} · سختی {card.difficulty}</span><strong>{player}، سه‌تاشو پیدا کن</strong></div><span className="threeScore">✓ {wins} · × {fails}</span></div><section className="threeCard"><span className="threeCategory">{card.category}</span><h1>{card.prompt}</h1>{phase!=="running"&&<div className="threeHostHint"><small>فقط برای مجری · نمونه جواب</small><span>{card.examples.join(" · ")}</span><em>نمونه‌اند؛ جواب درست دیگری هم می‌تواند قبول باشد.</em></div>}</section><div className={`threeClock ${danger?"danger":""} ${phase==="running"?"live":""}`}><small>{phase==="ready"?"سؤال رو خوندی؟":phase==="running"?"وقت داره می‌سوزه":"وقت تموم شد"}</small><strong>{phase==="ready"?"3.0":secs}</strong><span>ثانیه</span><div className="threeMeter"><i style={{transform:`scaleX(${Math.max(0,leftMs/THREE_SECOND_MS)})`}}/></div></div>{phase==="ready"&&<button className="primary threeGo" onClick={fire}>⚡ حالا! سه ثانیه</button>}{phase==="running"&&<p className="threeShout">سه‌تا! سه‌تا! سه‌تا!</p>}{phase==="judge"&&<div className="threeVerdict"><p>قبل از صفر، هر سه جواب کامل و معتبر گفته شد؟</p><div><button onClick={()=>verdict(false)}>💥 نه، سوخت</button><button onClick={()=>verdict(true)}>✓ گرفت!</button></div></div>}<div className="threeFooter"><span>رگ فعلی: <b>{streak}</b></span><button className="ghost" onClick={()=>setPhase("result")}>پایان بازی</button></div></GameShell>;
}
/* legacy QA marker: جوابی که بعد از صفر */
/* Rules: قوانین شروع بازی در PartySessionSetup نمایش داده می‌شود. */
